### ISSUE TITLE
New update does not install any tracks, immediately closes instead.

### ISSUE THREAD

**Issue by mativerval** [tim-morriss/pyscrapeTrain#5]
Hi, I am having to use the older release as when I try to use the updated version, no tracks get installed. Normally with the older version, I would just use for example `pyscrapetrain https://traktrain.com/ddertbag`. However, when I do that now I get an error that its not recognized as an internal command. When I try to install the tracks with the script directly using `pyscrapetrain.py https://traktrain.com/ddertbag`, an empty terminal opens up for a split-second and closes. I have attached a screenshot of what happens before the terminal closes. 
![x277089246-2b037aee-222a-46c0-9a17-bc6a6e48db59](https://github.com/user-attachments/assets/0c693203-3b34-4b0c-8041-af05f01430ad)
I know this behavior shouldn't be happening because when I use the script of the older release, a terminal opens up and I can still download 40 tracks.
![Screenshot 2023-10-21 001628asdasaaaa](https://github.com/tim-morriss/pyscrapeTrain/assets/141959751/b5ba5db8-2325-42b2-8171-48da8a4d4eca)
Is there something that I'm doing wrong? I am relatively new to python so I was wondering if there was something I'm missing.

**Comment by tim-morriss** [comment]
Hey, so I have updated the project to now function as a pip package, so you can't run it in the old way of  `python pyscrapetrain.py`.

Instead can you install the package using pip then try running the pyscrapetrain command?
`pip install pyscrapetrain`
Then
`pyscrapetrain https://traktrain.com/ddertbag` 

If that is still not working then it's an issue with the how the script is called on windows (I only tested on mac).
I can always update the script to work in the old way if that's an issue.

**Comment by tim-morriss** [comment]
I've just pushed a new change to the dev branch (you can access this if you've cloned the repo by using `git fetch origin` then `git checkout dev`) with a main.py file which allows you to start the script in the old way:

`python main.py https://traktrain.com/ddertbag`

Use this as a backup as the pip package method is the preferred way. Let me know how you get on and I'll close this issue.

**Comment by mativerval** [comment]
Hi, I get this error:
![Screenshot 2023-10-21 1202122](https://github.com/tim-morriss/pyscrapeTrain/assets/141959751/5c3093b5-8e66-4250-b88f-7a79b9f6cdd8)
I uninstalled and reinstalled the pip package, but I still get the error, "'pyscrapetrain' is not recognized as an internal or external command, operable program or batch file."

**Comment by tim-morriss** [comment]
Hey, so I have updated the dev branch again. I wrote something that should work on Windows too using the`python main.py` method.

Let me know if this fixes it.

**Comment by mativerval** [comment]
Hi sorry for the late response, this worked! I had to clone the repository again and install pick and validators first, but I can now download tracks without a limit. Thank you!
